spring:
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 100MB
    application.name: samplepcb_xpse
    elasticsearch:
        uris: http://localhost:9200
